language: java

jdk:
- oraclejdk8

script:
- ./gradlew check

after_success:
  - curl https://copilot.blackducksoftware.com/scripts/init/gradle -o bds_init.gradle
  - ./gradlew --init-script bds_init.gradle buildBom -DbdsPluginVersion=5.0.2
  - bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./build/blackduck/*_bdio.jsonld
